tuplel=(1,2,4,5,6)
print(tuplel)
print(tuplel[1])
print(tuplel[3:])
tuple2=()
print(tuple2)
tuple3=(1,)
print(tuple3)
print(type(tuple3))
tuple4=8*(8,)
print(tuple4)
temp=('狗杨','狗蛋','房子')
temp =temp[:1]+('二狗子',)+temp[1:]
print(temp)
print('%c'%97)
